<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Miroslava Guerrero">
<meta name="dcterms.date" content="2026-07-09">

<title>Marine Genomics Workshop 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="workshop3_metasm_files/libs/clipboard/clipboard.min.js"></script>
<script src="workshop3_metasm_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="workshop3_metasm_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="workshop3_metasm_files/libs/quarto-html/popper.min.js"></script>
<script src="workshop3_metasm_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="workshop3_metasm_files/libs/quarto-html/anchor.min.js"></script>
<link href="workshop3_metasm_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="workshop3_metasm_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="workshop3_metasm_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="workshop3_metasm_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="workshop3_metasm_files/libs/bootstrap/bootstrap-547d8881d88612430a2cfac5ecb41a19.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Marine Genomics Workshop 3</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Miroslava Guerrero </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="workshop-3---metagenome-assembly" class="level1">
<h1>Workshop 3 - Metagenome assembly</h1>
<p>In this workshop we will assemble a mock metagenome consisting of five bacterial species, which is very simple compared to a real metagenome. Regardless it has been designed to capture some key challenges that are inherited when assembling a metagenome. This includes variable coverage and similar sequences.</p>
<p>For the purposes of metagenomic assembly we note the number of chromosomes, total genome size and its GC content.</p>
<p>When assembling a full metagenomic assembly there will be two additional steps from when we assemble a single bacterial genome. Binning and Bin assessment which are unique to metagenome assembly. The steps are as follows:</p>
<ol type="1">
<li>Examine Reads</li>
<li>Assembly</li>
<li>Basic assembly QC</li>
<li>Binning</li>
<li>Bin assessment</li>
</ol>
<section id="examine-reads" class="level2">
<h2 class="anchored" data-anchor-id="examine-reads">1. Examine Reads</h2>
<p>Input data for this exercise consists of simulated reads from an Oxford Nanopore MinION sequencer, the data were simulated using a program called Badread.</p>
<p>Make a new sub directory called raw_reads. Then make a symbolic link to the raw reads file in this directory. Afterwards we can check that all files are correct by using the ls command and -l to show extended details on each file.</p>
<section id="read-length-distribution" class="level3">
<h3 class="anchored" data-anchor-id="read-length-distribution">Read length distribution</h3>
<p>During the assembly process we will take shorter sequences (reads) and attempt to join them into longer sequences, an important determinant of success is the size of the raw reads themselves.</p>
<p>Firstly we need to examine the read length distribution in the input data. The following code unzips the raw data and selects the top 40k lines in the file, and prints the outputs into a file called read_lengths.txt</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">zcat</span> raw_data/raw_reads.fastq.gz <span class="kw">|</span> <span class="fu">head</span> <span class="at">-n</span> 40000 <span class="kw">|</span> <span class="ex">bioawk</span> <span class="at">-c</span> fastx <span class="st">'{print $name,length($seq)}'</span> <span class="op">&gt;</span> read_lengths.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we create a plot to visualize the read lengths.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>rl_data <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"read_lengths.txt"</span>,<span class="at">col_names =</span> <span class="fu">c</span>(<span class="st">"id"</span>,<span class="st">"length"</span>), <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of read lengths in the mock nanopore sequencing dataset</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rl_data, <span class="fu">aes</span>(<span class="at">x=</span>length<span class="sc">/</span><span class="dv">1000</span>)) <span class="sc">+</span> </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Read Length Kb"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Number of Reads"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="workshop3_metasm_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="calculating-read-n50" class="level3">
<h3 class="anchored" data-anchor-id="calculating-read-n50">Calculating read N50</h3>
<p>Based on the plot above it is clear that the majority of reads are between 1 and 50kb in length. To summarize this we can use the N50 statistic, although it is more commonly used to summarize genome assemblies, it is also useful for summarizing read length distributions.</p>
<p>N50 is useful as it is unaffected from having a large number of tiny reads and instead places greatest emphasis on the longer reads in the data. We will calculate the read N50 of the sample reads by following the next steps:</p>
<ol type="1">
<li>Rank all reads from longest to shortest</li>
<li>Create a new column with the cumulative sum of read lengths (starting with the longest)</li>
<li>Find the read at which the cumulative sum surpass 50% of the total read volume (ie. total sum of all read lengths)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>total_len <span class="ot">&lt;-</span> <span class="fu">sum</span>(rl_data<span class="sc">$</span>length)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>rl_data <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(length)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cumsum =</span> <span class="fu">cumsum</span>(length)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(cumsum<span class="sc">&gt;</span>total_len<span class="sc">/</span><span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="at">n=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  id                                        length   cumsum
  &lt;chr&gt;                                      &lt;dbl&gt;    &lt;dbl&gt;
1 c96c1300-8177-e260-d9bd-2fdf75d0146b_2040  22322 74486252</code></pre>
</div>
</div>
<p>The above row describes a single sequencing read which is 22,322 bp long, and cumsum (cumulative sum of read lengths) is often used to figure out thing like “how many of my longest reads do i need to reach X times genome coverage”, here it indicates that the running total of all read lengths so far reaches 74,486,252 bp.</p>
<p>We see here that the N50 of individual reads is about 22kb, which needs to be kept in mind as we perform assembly, and expect that the N50 of the assembly should be considerably grater than this.</p>
</section>
</section>
<section id="assembly" class="level2">
<h2 class="anchored" data-anchor-id="assembly">2. Assembly</h2>
<p>Assuming that we are satisfied with the overall quality of our reads, the first step is to assemble them using flye, as it is probably the best assembler for long-read metagenome data. We will firstly make a flye directory (mkdir) in the project folder and change directory (cd) to this new flye directory and run all flye commands from within this directory.</p>
<p>We will run flye on the simulated data. First we create a new shell script, save it, run it, and monitor the job output (tail -f slurm-xxx.out). Flye will report the read N50, which we can compare with the value we computed earlier.</p>
<p>Once the flye has finished running the outputs will be available in the directory mock. Key outputs are: - assembly.fasta = The actual assembled contigs - assembly_graph.gfa = representation of the assembly graph in gfa format (to be used in bandage) - assembly_graph.gv = assembly graph in graphviz format - assembly_info.txt = table of information on each contig.</p>
<section id="visualize-the-assembly-using-bandage" class="level3">
<h3 class="anchored" data-anchor-id="visualize-the-assembly-using-bandage">Visualize the assembly using bandage</h3>
<p>Q1. What is the size and coverage of the largest contig in the assembly? Length: 4,681,059 bp Depth:21.0x</p>
<p>Q2. The assembly should contain at least one (or several) large circular contigs. Based on size and coverage you can guess which contig corresponds to the genome of the most abundant species in the mock community?</p>
</section>
<section id="chromosome-lengths-and-gc-content-in-the-reference-data" class="level3">
<h3 class="anchored" data-anchor-id="chromosome-lengths-and-gc-content-in-the-reference-data">Chromosome lengths and GC content in the reference data</h3>
<p>We will compare the assembled contigs with reference genomes from the five species that comprise our mock community by tabulating chromosome lengths and their corresponding GC content.</p>
<p>Locating two circular chromosomes for Vibrio alfacsensis in bandage, using the outputs from gc.awk to help with it.</p>
<p>Based on the table the four sequences that match to Vibrio based on the GC, the largest ones are the bacterial chromosomes, whereas the plasmids are the smaller ones. AP024165.1 (3,168,162 bp; 44% GC) and AP024166.1 (1,553,697 bp; 44% GC) are the clearly larger ones and circular chromosomes</p>
</section>
</section>
<section id="basic-assembly-qc" class="level2">
<h2 class="anchored" data-anchor-id="basic-assembly-qc">3. Basic assembly QC</h2>
<p>Previously we used gc.awk to print the length and GC content for reference sequences, now we do the same for the assembled contigs.</p>
<p>Now we can create some plots in R to explore the GC content and coverage depth of contigs. Two of the most useful statistics for grouping cotigs from the same species toghetehr are the GC content and the coverage depth, because these should generally be similar for contigs derived from the same chromosome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>gc <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"assembly_check/assembly.gc.tsv"</span>,<span class="at">col_names =</span> <span class="fu">c</span>(<span class="st">"#seq_name"</span>,<span class="st">"length"</span>,<span class="st">"GC"</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>info <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"flye/mock/assembly_info.txt"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># join datasets using seq_name</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>gc_info <span class="ot">&lt;-</span> info <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(gc)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># plot - histogram of GC content values for assembled contigs in a flye assembly of the mock community dataset</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>gc_info <span class="sc">%&gt;%</span> </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>GC)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Number of contigs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="workshop3_metasm_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The following code and graph display a plot of GC vs coverage which helps identify clusters that have similar values for both parameters. By making this plot we filter the data to remove contigs with unrealistically high GC content and very high coverage depth (probably repeats)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot - coverage and GC content assembled contigs in the mock community assembly. Contig lengths are shown through point size</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>gc_info <span class="sc">%&gt;%</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(GC<span class="sc">&lt;</span><span class="fl">0.8</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(cov.<span class="sc">&lt;</span><span class="dv">25</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>GC,<span class="at">y=</span>cov.)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size=</span>length)) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Coverage depth"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="workshop3_metasm_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># adding labels to look at the contigs with highest coverage and compare with contigs in bandage.</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>gc_info <span class="sc">%&gt;%</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(GC<span class="sc">&lt;</span><span class="fl">0.8</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(cov.<span class="sc">&lt;</span><span class="dv">25</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>GC,<span class="at">y=</span>cov.)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size=</span>length)) <span class="sc">+</span> <span class="fu">geom_label_repel</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="st">`</span><span class="at">#seq_name</span><span class="st">`</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="workshop3_metasm_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The cluster of contigs with high GC content (&gt;60%) points towards Desulfovibrio sulfodismutans, while the coverage depth around 7.5x is likely to correspond to a different species, Vibrio algicola, with a much lower GC content</p>
<section id="assembly-size-vs-reference-size" class="level3">
<h3 class="anchored" data-anchor-id="assembly-size-vs-reference-size">Assembly size vs reference size</h3>
<p>Since the mock metagenome has a precisely known composition we can asses its completeness by comparing the length of our assembly with that of the reference. Which can be done from within our top-level project directory.</p>
<p>Firstly we calculate the total length of our reference sequences. Which tells us the total length is around 24Mb.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> /pvol/data/mg/refs/<span class="pp">*</span>.fna <span class="kw">|</span> <span class="ex">bioawk</span> <span class="at">-c</span> fastx <span class="at">-f</span> gc.awk <span class="kw">|</span> <span class="fu">awk</span> <span class="st">'{sum+=$2}END{print sum}'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="binning" class="level2">
<h2 class="anchored" data-anchor-id="binning">4. Binning</h2>
<p>One of the most challenging tasks in metagenomic assembly is separating sequences from many different organisms present in the sample. The tools that can be used fall into two categories: 1. Read binning tools - group the raw (unassembled) reads 2. Contig binning tools - group assembled contigs</p>
<p>In both cases the resulting outputs are bins, and each of these contain multiple distinct sequences (reads or contigs) that come from the same organism. Common errors from binning include: 1. Placing two sequences together when they come from different taxa - leads to contamination 2. Failing to group sequences that come from the same taxon - leads to fragmentation.</p>
<p>For this exercise we will perform contig binning since we have long-reads and can rely on metaFlye to assemble high quality contigs from a mixed collection of reads.</p>
<p>By using the program metabat2, which tries to group contigs based on nucleotide composition and read coverage, and uses the tetranucleotide frequency as well. For simplicity we will use the coverage information calculated by flye and provide it to metabat.</p>
<p>Firstly we create a directory for our binning work and change to it. Creating the metabat directory within the top-level of the project.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># input file summarising read depth info for all contigs</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> ../flye/mock/assembly_info.txt  <span class="kw">|</span> <span class="fu">grep</span> <span class="at">-v</span> <span class="st">'#'</span> <span class="kw">|</span> <span class="fu">awk</span> <span class="st">'{OFS="\t";print $1,$3}'</span> <span class="op">&gt;</span> depths.txt</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># crate new version of the assembly file in which the contigs have the same order as those in the depths.txt file</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> depths.txt <span class="kw">|</span> <span class="fu">awk</span> <span class="st">'{print $1}'</span> <span class="kw">|</span> <span class="fu">xargs</span> samtools faidx ../flye/mock/assembly.fasta <span class="op">&gt;</span> assembly_ordered.fasta</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># run metabat </span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="ex">metabat2</span> <span class="at">-i</span> assembly_ordered.fasta <span class="at">-a</span> depths.txt <span class="at">--cvExt</span> <span class="at">-o</span> bins/metabat <span class="at">--seed</span> 5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The bins directory will contain multi-fasta files with each of the bins inferred by metabat. To inspect which contigs were grouped into which bin we can use the command grep.</p>
<p>From the output we can see that metabat has grouped contigs into 5 bins. If we compare the contigs in these bins with those shown in bandage we can see that the largest and highest coverage contig were not included.</p>
</section>
<section id="check-bin-quality-with-checkm" class="level2">
<h2 class="anchored" data-anchor-id="check-bin-quality-with-checkm">5. Check bin quality with checkM</h2>
<p>The program checkM will be used to assess the quality of our bins. Each of these bins generated by metabat should represent a single species or strain within our community. The goal now is to create bins in which: 1. The sequences within the bin contain the complete sequence for this organism 2. The sequences within the bin all come from the same organism and are not contaminated with sequences from other taxa.</p>
<p>We can assess the degree to which our binning and assembly has achieved these goals by using checkM. We first create a directory within the top level of the project folder for running checkM and change into it.</p>
<p>Here we prepare inputs for checkM, copying over the bins from metabat. We also need to include the longest contig in bins, we extract this contig from our assembly and include it with our metabat bins.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># largest contig number might change.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="ex">samtools</span> faidx ../flye/mock/assembly.fasta contig_28 <span class="op">&gt;</span> bins/contig_28.fa</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Afterwards create a slurm job script and save it within the checkm directory, and then run the file. After it finishes processing the file look at the resulsts. It will include a summary of the results for each of the bins, including: - Marker Lineage (approximate taxonomic classification) - no. genomes (no. of reference genomes used to infer marker set) - no. markers (no. inferred marker genes) - no. sets (no. inferred co-located marker sets) - 0-5+ (no. of times each marker gene is identified) - Completeness (calculated by taking the no. marker genes appearing exactly 1 time and divided by the total) - Contamination (no. of marker genes appearing &gt;1 times divided by the total) - Strain heterogeneity (calculated by examining the marker genes appearing &gt;1 times and determining the proportion of these that are from the same or very similar organisms/strains)</p>
<section id="question-which-bin-has-the-highest-level-of-contamination-and-why-might-this-be" class="level3">
<h3 class="anchored" data-anchor-id="question-which-bin-has-the-highest-level-of-contamination-and-why-might-this-be">QUESTION: Which bin has the highest level of contamination? and why might this be?</h3>
<p>The bin with the highest level of contamination is ” metabat.5” classified as f__Vibrionaceae (UID4865) with a contamination of 1.33%. It has the highest contamination because it is likely that the mock community contains two closely related Vibrio species, which share many similar marker genes. This can be supported by the strain heterogeneity value (26.09%), suggesting the contamination arises from closely related stains grouped into the same bin.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>